// <auto-generated />
using System;
using BeeCloud.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeeCloud.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911103154_AddHealthChecks")]
    partial class AddHealthChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeeCloud.Domain.Entities.ComputeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GpuCount")
                        .HasColumnType("integer");

                    b.Property<string>("GpuModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("compute_nodes", (string)null);
                });

            modelBuilder.Entity("BeeCloud.Domain.Entities.HealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComputeNodeId")
                        .HasColumnType("uuid");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpuTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpuUsagePercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ComputeNodeId", "CheckedAt");

                    b.ToTable("health_checks", (string)null);
                });

            modelBuilder.Entity("BeeCloud.Domain.Entities.Network", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("networks", (string)null);
                });

            modelBuilder.Entity("BeeCloud.Domain.Entities.NetworkAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComputeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.HasIndex("ComputeNodeId", "NetworkId")
                        .IsUnique();

                    b.ToTable("network_attachments", (string)null);
                });

            modelBuilder.Entity("BeeCloud.Domain.Entities.HealthCheck", b =>
                {
                    b.HasOne("BeeCloud.Domain.Entities.ComputeNode", null)
                        .WithMany()
                        .HasForeignKey("ComputeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeeCloud.Domain.Entities.NetworkAttachment", b =>
                {
                    b.HasOne("BeeCloud.Domain.Entities.ComputeNode", null)
                        .WithMany()
                        .HasForeignKey("ComputeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeeCloud.Domain.Entities.Network", null)
                        .WithMany()
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
