apiVersion: v1
kind: Secret
metadata:
  name: beecloud-app-secrets
  namespace: beecloud
type: Opaque
stringData:
  POSTGRES_DB: beecloud
  POSTGRES_USER: beecloud
  POSTGRES_PASSWORD: beecloud_dev_password

  BeeCloudDatabase: "Host=postgres;Port=5432;Database=beecloud;Username=beecloud;Password=beecloud_dev_password"