apiVersion: batch/v1
kind: Job
metadata:
  name: beecloud-migrations
  namespace: beecloud
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrations
          image: beecloud-migrations:dev
          imagePullPolicy: IfNotPresent

          env:
            - name: ConnectionStrings__BeeCloudDatabase
              valueFrom:
                secretKeyRef:
                  name: beecloud-app-secrets
                  key: BeeCloudDatabase

          command:
            - dotnet
            - ef

          args:
            - database
            - update
            - --project
            - src/BeeCloud.Infrastructure
            - --startup-project
            - src/BeeCloud.Api